// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PkgdefLanguage
{
    internal sealed partial class Vsix
    {
        public const string Id = "06278dd5-5d9d-4f27-a3e8-cd619b101a50";
        public const string Name = "Pkgdef Language";
        public const string Description = @"Full language support with IntelliSense, validation, outlining, and more for .pkgdef and .pkgundef files";
        public const string Language = "en-US";
        public const string Version = "1.4.1004";
        public const string Author = "Mads Kristensen";
        public const string Tags = "vsix, pkgdef, textmate";
        public const bool IsPreview = false;
    }
}
