// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PkgdefLanguage
{
    internal sealed partial class Vsix
    {
        public const string Id = "06278dd5-5d9d-4f27-a3e8-cd619b101a50";
        public const string Name = "Pkgdef Language";
        public const string Description = @"Basic language support for .pkgdef and .pkgundef files";
        public const string Language = "en-US";
        public const string Version = "1.2.999";
        public const string Author = "Mads Kristensen";
        public const string Tags = "vsix, pkgdef, textmate";
    }
}
