// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PkgdefLanguage
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EditorFactoryString = "57522df2-e926-4908-8c62-d57afece26e3";
        public static Guid EditorFactory = new Guid(EditorFactoryString);

        public const string PkgdefLanguageString = "4ecd0189-a643-49a1-9f2a-6f32e299dd7b";
        public static Guid PkgdefLanguage = new Guid(PkgdefLanguageString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {

    }
}